### ISSUE TITLE
Is there a process in place for others to suggest/request changes?

### ISSUE THREAD

**Issue by trosel** [Shavian-info/readlex#2]
Maybe it is as simple as opening a Pull Request and discussing in the comments of the pull request?

If so, which files need to be changed? Which is the "master" file, the `.dict` files or the `.tsv` file?

**Comment by Shavian-info** [comment]
The simplest way for now is to open issues requesting changes. In the case of the ReadLex proper, I like to update both the .tsv and the .dict file in parallel. Pull requests are possible, but I won't approve any changes that deviate from the spelling principles outlined on [Shavian.info](https://www.shavian.info/dictionary/). So it will depend how confident you are in being able to follow those.

**Comment by trosel** [comment]
Thanks for the response!

I am mainly thinking of adding things like common acronyms, proper names, etc.

Stuff that people may want to search for, for example. Maybe most of that would go in the addendum, but i’m not sure if the addendum is easily searchable like the main file is.

**Comment by Shavian-info** [comment]
The addendum isn't really intended to be searchable in its raw format. Someone could make an app or website to search it, but that is beyond my skill. 

Acronyms are really difficult since they can stand for multiple things quite commonly: is 'ABC' the Australian Broadcasting Corporation, the American Broadcasting Company, Anti-Bribery and Corruption, 'Almond, Brazil and Cashew' (nuts), etc.? This is why I add them to addendum.dict now and not the Read Lexicon proper. 

Personal names, equally, are so variable. The Shavian principle is to spell a person's name as they themself spell it (or at least as they pronounce it).

These sorts of ephemeral/highly variable words will go in the Addendum for now.

**Comment by Shavian-info** [comment]
I've now enabled 'discussions' for the ReadLex repository, if you'd prefer to discuss suggestions and ideas without opening issues.
