### ISSUE TITLE
Using of 𐑼 in 'library' 𐑤𐑲𐑚𐑮𐑼𐑦 and 'dictionary' 𐑛𐑦𐑒𐑖𐑩𐑯𐑼𐑦

### ISSUE THREAD

**Issue by kolokol-sa** [Shavian-info/readlex#24]
Its using totally corresponds with the pronunciation, but I find it unnatural to use 𐑼 here.
The word naturally splits into syllables, in this case 'laɪ-brə-ri' and 'dɪk-ʃə-nə-ri'. When we spell word like 𐑤𐑲𐑚𐑮𐑼𐑦 instead of 𐑤𐑲𐑚𐑮𐑩𐑮𐑦 and 𐑛𐑦𐑒𐑖𐑩𐑯𐑼𐑦 instead of 𐑛𐑦𐑒𐑖𐑩𐑯𐑩𐑮𐑦, it breaks this logic and we cannot split the word up into syllables anymore, because they are now merged together in this letter.

The similar issue is already mentioned in an 'affix rule', but I suggest it to be extended to 'syllable rule'.

I suspect that it would require much effort to fix and it likely affects much more words than these two (and other compound letters). And maybe it's the matter of taste, so I just raise a question to discuss.

**Comment by kolokol-sa** [comment]
Yes, and one more thing, compound letter were created to avoid the spelling differences for speakers of rhotic and non-rhotic accents. So a compound letter implies an optional /r/-sound that can be omitted in RP and other non-rhotic accents. In case I mentioned, this /r/ can't be omitted and it's meaningful, so I feel that we should use 2 letters instead of a compound one.

**Comment by mwgamera** [comment]
I want to neither oppose nor support your proposal, but

> So a compound letter implies an optional /r/-sound that can be omitted in RP

You are mistaken here. When I first learned about Shavian I also thought this is the case, but it is not. Despite being sometimes called separate letters by Kingsley and others (and mistakenly being encoded as such in Unicode), all the r-compounds are used like purely typographic ligatures orthographically equivalent to the sequences of their constituent parts. Consider for example 𐑓𐑹𐑩𐑥 _forum_ or 𐑜𐑤𐑹𐑦 _glory_ which were spelled this way in Androcles, or even the keyword 𐑼𐑱 _array_ itself. Choice of which letters have ligatures was clearly driven by dialectical differences, but that's about it. It seems to be true that, at least statistically, if the 𐑮 is dropped, then it is a part of a ligature, but converse is demonstrably false. Ligature is always used no matter whether or not the 𐑮 is pronounced in non-rhotic dialects.

Of course, this doesn't preclude having typographic rules about when to use and when to refrain from using ligatures. The rule used in practice is similar to the one used in Fraktur. Avoiding ligatures across certain morpheme boundaries makes a word with a suffix look like a word with a suffix, which is nice. I think it also helps with hyphenation across line breaks.

As for syllables, consider that there is a lot of disagreement how to properly divide English words. The most commonly followed maximal onset principle puts a syllable break right in the middle of the 𐑼 ligature in the word 𐑼𐑱 (𐑩.𐑮𐑱) which was the keyword given in Androcles' tables for that ligature. American dictionaries don't follow this principle and say the syllables are lī-brĕr-ē and dĭk-shə-nĕr-ē (in AHD respelling) so neither of those 𐑼 in _library_ and _dictionary_ is at syllable break according to them.
Additionally, the word _dictionary_ has just three syllables in RP. Cambridge 17th ed. gives it as a second pronunciation: ˈdɪk.ʃᵊn.ᵊr.i, -ʃᵊn.ri. Note how all these schwas are marked optional so even in pronunciation with 4 syllables that 𐑩 might just be there to mark syllabic 𐑮 rather than an actual schwa sound. Orthographic lawyering aside, it surely makes sense to join it into single 𐑼 compound then, right?

**Comment by Shavian-info** [comment]
I can't really put it any better than @mwgamera. The disagreement between dialects about where syllable breaks actually are is the clincher for me; rhotic speakers and non-rhotic speakers tend to have very different instincts about this.

It would therefore further increase the memorisation requirements to make the distinction on a syllable-by-syllable basis. I developed the affix rule because this seemed to reflect what Kingsley Read did in practice (although I haven't found anywhere where he described it), and because there were a few edge cases where the absurdity was obvious, like 𐑦𐑯𐑓𐑮𐑼𐑧𐑛, versus 𐑦𐑯𐑓𐑮𐑩𐑮𐑧𐑛.
