### ISSUE TITLE
Banshee

### ISSUE THREAD

**Issue by trosel** [Shavian-info/readlex#25]
According to Cambridge, both UK and US stress Banshee on the first syllable. 

For that reason, I believe this word should be spelled 𐑚𐑨𐑯𐑖𐑦 instead of 𐑚𐑨𐑯𐑖𐑰

**Comment by Shavian-info** [comment]
True, but the final vowel in RP is the long vowel /iː/ so is represented by 𐑰 — see also 'Androcles' which is stressed on the first syllable. Final 𐑦 represents the allophonic /i/ (no vowel length marker).

**Comment by trosel** [comment]
Hm.. so maybe “banshee” is sort of equally stressed on both syllables then…

**Comment by mwgamera** [comment]
It's not really possible for it to consist of two equally stressed syllables. The implication goes only in one direction: a weak vowel might appear only in an unstressed syllable, but the converse isn't true. There are some pronunciation models that describe it differently (something about tertiary stress), but usually it's accepted that unreduced vowels might appear in both stressed and unstressed syllables.
Since English stress patters are fairly regular, you can often reconstruct it from the position of weak vowels in Shavian spelling, but it's not infallible. Both ˈbænʃiː and bænˈʃiː are spelled the same 𐑚𐑨𐑯𐑖𐑰 because unstressed 𐑰 is still 𐑰 unless it's actually weakened into a different vowel which is not happening here.
That being said, it might be a good idea to update the IPA field to say ˈbænʃiː as that's more common pronunciation according to all dictionaries I checked (Cambridge 17th ed. lists both but gives the one with accent on the first syllable first).

**Comment by trosel** [comment]
Thank you for the further info. I thought that 𐑰 was always stressed sort of like the "up" letter.

**Comment by Shavian-info** [comment]
> It's not really possible for it to consist of two equally stressed syllables. The implication goes only in one direction: a weak vowel might appear only in an unstressed syllable, but the converse isn't true. There are some pronunciation models that describe it differently (something about tertiary stress), but usually it's accepted that unreduced vowels might appear in both stressed and unstressed syllables. Since English stress patters are fairly regular, you can often reconstruct it from the position of weak vowels in Shavian spelling, but it's not infallible. Both ˈbænʃiː and bænˈʃiː are spelled the same 𐑚𐑨𐑯𐑖𐑰 because unstressed 𐑰 is still 𐑰 unless it's actually weakened into a different vowel which is not happening here. That being said, it might be a good idea to update the IPA field to say ˈbænʃiː as that's more common pronunciation according to all dictionaries I checked (Cambridge 17th ed. lists both but gives the one with accent on the first syllable first).

Sure, I'll switch the stress to the first syllable.

**Comment by Shavian-info** [comment]
> Thank you for the further info. I thought that 𐑰 was always stressed sort of like the "up" letter.

It's a good rule of thumb for North American English speakers, but there is a vowel length distinction in other parts of the world. I don't want to claim to be too definitive on this since the allophone /i/ in RP is a topic of some debate from what I can see. But Androcles and the Lion is pretty clear and I'm pretty open that that's the starting point for the Read Lexicon.
