### ISSUE TITLE
"again"

### ISSUE THREAD

**Issue by trosel** [Shavian-info/readlex#28]
"Again" is currently listed as "𐑩𐑜𐑱𐑯". It seems like it should be one of those words that shows multiple pronunciations.

Even in the UK it seems as though 𐑩𐑜𐑧𐑯 has become the more common pronunciation.

**Comment by Shavian-info** [comment]
Yes, there's probably a good case to prioritise 𐑩𐑜𐑧𐑯 for mutual intelligibility. I've hesitated because Androcles clearly uses 𐑩𐑜𐑱𐑯 and I wondered if this fit under the 'favour the strong pronunciation' principle set out Androcles. On review, I suspect it doesn't since 𐑩𐑜𐑧𐑯 and 𐑩𐑜𐑱𐑯 are alternative pronunciations that aren't dependent on the overall stress pattern of a sentence. So I'll think about this.

**Comment by trosel** [comment]
> the 'favour the strong pronunciation' principle set out Androcles

can you say more about what this is?

**Comment by Shavian-info** [comment]
The vowels in some common words are often reduced when used in sentences, e.g. 𐑞𐑨𐑑 becomes 𐑞𐑩𐑑, 𐑸 becomes 𐑼, etc. Shavian analyses pronunciation at the word-by-word level, not the sentence level, so gives these common words their fuller pronunciation. Note, this isn't about sounding at words at a syllable-by-syllable level which would give very artificial pronunciations. You can read more in [Androcles 'notes on spelling'](https://archive.org/details/AndroclesAndTheLion_ShawAlphabetEdition/page/n71/mode/2up), principle 2.

**Comment by trosel** [comment]
Maybe that is why “what” is spelled 𐑢𐑪𐑑 instead of 𐑢𐑳𐑑

**Comment by JapanYoshi** [comment]
Nah, that’s more like “because”: 𐑚𐑦𐑒𐑳𐑟 American, 𐑚𐑦𐑒𐑪𐑟 British.

**Comment by Shavian-info** [comment]
Okay, I've changed 'again' and 'against' to default to 𐑩𐑜𐑧𐑯 and 𐑩𐑜𐑧𐑯𐑕𐑑, given these now appear to be the most common pronunciations in both RP and GA.
