### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by mwgamera** [Shavian-info/readlex#36]
It's certainly one of these words for which multiple Shavian spellings need to be accepted, but if I understand the 3rd rule of the spelling principles—“Choose the RP pronunciation closest to General American”—it appears that the ReadLex spelling of _schedule_ and related words should use 𐑕𐑒- rather than 𐑖-. Of course, it depends on how exactly you define RP and GA, so I might be wrong.
There is also a discrepancy in treatment of // j // where _scheduled_ is currently 𐑖𐑧𐑡𐑵𐑤𐑛 but _unscheduled_ is 𐑳𐑯𐑖𐑧𐑛𐑿𐑤𐑛. The web interface also gives 𐑳𐑯𐑖𐑧𐑛𐑵𐑤𐑛 as supposedly GA which seems completely wrong as well.

**Comment by Shavian-info** [comment]
Thanks for picking up the inconsistency. The 𐑕𐑒𐑧𐑛𐑿𐑤 pronunciation is still controversial outside the US and considered by many to be an Americanism. It seems to be much more accepted among younger speakers. But for now, I'll stick with 𐑖𐑧𐑛𐑿𐑤 and note the General American alternative 𐑕𐑒𐑧𐑛𐑿𐑤. The weirdness of 'unscheduled' arose simply because in preparing a dictionary with so many entries, some automation is required and this one slipped through.
