### ISSUE TITLE
“sewer” should be 𐑕𐑵𐑼, but is 𐑕𐑫𐑼

### ISSUE THREAD

**Issue by HaleyHalcyon** [Shavian-info/readlex#89]
CUBE lists “sewer” with GOOSE+lettER[*](http://seas.elte.hu/cube/index.pl?s=sewer&t=&syllcount=&maxout=&wfreq=0-9&grammar=), but Readlex has it with CURE.

**Comment by mwgamera** [comment]
Cambridge has: **sewer** _drain_ sʊəʳ, sjʊəʳ (US) ˈsuː.ɚ 
And that's probably why ReadLex has that too. But it doesn't seem right indeed. All the other sources I checked seem to agree on  /⁠(j)uː⁠/ and I couldn't find any obvious evidence on the Youglish of it ever being anything else. So I also agree that 𐑕𐑵𐑼 would be more recognizable to everyone.

It's probably easily confusable with CURE in post-RP-like dialects, though. If you look at [Lindsey's post about it](https://www.englishspeechservices.com/?p=3293), you'll see that /⁠ʉw.⁠ə⁠/ is one of possible realizations of CURE (fate 2). Here CUBE generally follows whatever SSB does and even the word ‘cure’ itself is transcribed with /⁠oː⁠/ as in THOUGHT rather than with the distinct CURE phoneme /⁠ɵː⁠/ (cf. ‘secure’). But I think all the words that met the second fate are indeed transcribed only with the smoothed /⁠ɵː⁠/ in CUBE rather than with /⁠ʉwə⁠/ as in ‘sewer’.

**Comment by Shavian-info** [comment]
Thanks for picking this up. Cambridge is anomalous. Oxford has /suːə(r)/ and it is more universally understandable. Note, 'sewerage' remains with the CURE vowel.
